---
- name: Ensure old versions of Docker are not installed.
  apt:
    pkg:
      - docker
      - docker-engine
      - docker.io 
      - containerd 
      - runc
    state: absent

- name: Ensure dependencies are installed.
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - gnupg2
      - curl
      - gnupg-agent
      - software-properties-common
    state: present

- name: Add Docker apt key.
  apt_key:
    url: "{{ docker_apt_gpg_key }}"
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    keyring: "{{ docker_apt_gpg_key_path }}"
    state: present

- name: Add Docker repository.
  apt_repository:
    repo: "{{ docker_apt_repository }}"
    filename: docker
    state: present
    update_cache: true